/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 StandNexus.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/StandNexus.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.006']} position={[-0.132, -0.055, 0]} scale={[0.64, 1, 1.4]} />
      <group position={[-0.656, 0.19, 0.45]} scale={[1, 1.22, 1.26]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials['Material.009']} />
      </group>
      <group position={[0.059, 0.229, 0.963]} rotation={[0, 1.24, 0]} scale={[1, 0.74, 0.73]}>
        <mesh geometry={nodes.Cube017.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cube017_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials['Material.017']} />
      </group>
      <group position={[-0.656, 0.814, -0.85]} scale={[1, 1.31, 1.5]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube019_3.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-0.656, 0.814, -0.85]} scale={[1, 1.31, 1.5]}>
        <mesh geometry={nodes.Cube020.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cube004.geometry} material={materials.Material} position={[0.285, 0.633, -0.105]} scale={[6.31, 0.34, 2.77]} />
    </group>
  )
}

useGLTF.preload('/StandNexus.gltf')
